### ISSUE TITLE
Clue area is missing on game start, first player

### ISSUE THREAD

**Issue by MeGotsThis** [Hyphen-ated/MakeHanabiGreatAgain#21]
![image](https://cloud.githubusercontent.com/assets/9635309/15883047/a47f995c-2cf9-11e6-998f-e18596b964d0.png)

2nd games this happened. First game happened to someone else. For both games, it only involved the first player.

**Comment by Aroma1997** [comment]
Had the same problem.

**Comment by MeGotsThis** [comment]
![image](https://cloud.githubusercontent.com/assets/9635309/15982974/5a939cfc-2f4d-11e6-8dec-9a618446038f.png)

First game of the day/browser load

**Comment by Hyphen-ated** [comment]
pretty sure this has been fixed
